name: Build DLL

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Compile
        run: cl /LD /O2 /MT Dll1.cpp user32.lib

      - uses: actions/upload-artifact@v4
        with:
          name: Dll1
          path: Dll1.dll
